import {ideas,templates} from './product-data.js';
import {compileWithPromptMaster} from './prompt-master-runtime/compiler.js';

const $=s=>document.querySelector(s);
const screen=$('#screen'),menu=$('#menuSheet'),backdrop=$('#sheetBackdrop'),menuBtn=$('#menuButton'),toast=$('#toast');
const state={screen:'home',idea:'',goal:'build',priorities:[],target:'auto',step:1,result:'',meta:null,clarifications:[],clarificationAnswers:[],theme:localStorage.getItem('pp-theme')||'system'};

const goalOptions=[['build','Build something','App, website, feature, tool or workflow'],['improve','Improve or fix','Upgrade an existing product, prompt or behavior'],['research','Research or compare','Find, evaluate and recommend'],['create','Create content','Writing, image, video or another creative output']];
const priorityOptions=[['premium','Premium polish'],['simple','Keep it simple'],['mobile','Mobile-first'],['privacy','Privacy-first'],['fast','Fast & efficient'],['exact','Strict requirements'],['versatile','Versatile / reusable'],['commercial','Commercial quality']];
const targetOptions=[['auto','Let Perfect Prompt choose','Detect the task and use the strongest Prompt Master route'],['agent','Coding / agent tool','Codex, Claude Code, Cursor, Arena, Lovable and similar'],['chat','General AI chat','ChatGPT, Claude, Gemini, Grok and similar'],['visual','Image / video AI','Image, video and creative generation tools']];

const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1900)}
function setTheme(theme){state.theme=theme;localStorage.setItem('pp-theme',theme);document.documentElement.dataset.theme=theme;syncThemeButtons()}
function syncThemeButtons(){document.querySelectorAll('[data-quick-theme],[data-theme-choice]').forEach(b=>b.classList.toggle('on',(b.dataset.quickTheme||b.dataset.themeChoice)===state.theme))}
function openMenu(){menu.classList.add('open');menu.setAttribute('aria-hidden','false');backdrop.hidden=false;menuBtn.setAttribute('aria-expanded','true');syncThemeButtons()}
function closeMenu(){menu.classList.remove('open');menu.setAttribute('aria-hidden','true');backdrop.hidden=true;menuBtn.setAttribute('aria-expanded','false')}
function go(name){state.screen=name;closeMenu();render();window.scrollTo({top:0,behavior:'smooth'})}
function clearClarifications(){state.clarifications=[];state.clarificationAnswers=[]}
function loadStarter(text){state.idea=text;state.step=1;state.priorities=[];state.target='auto';state.meta=null;clearClarifications();go('home');setTimeout(()=>$('#ideaInput')?.focus(),30);showToast('Loaded into generator')}
function startNew(){state.idea='';state.goal='build';state.priorities=[];state.target='auto';state.step=1;state.result='';state.meta=null;clearClarifications();go('home')}

setTheme(state.theme);
menuBtn.addEventListener('click',openMenu);$('#menuClose').addEventListener('click',closeMenu);backdrop.addEventListener('click',closeMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.menu)));
document.querySelectorAll('[data-quick-theme]').forEach(b=>b.addEventListener('click',()=>{setTheme(b.dataset.quickTheme);showToast(`${b.textContent} theme`)}));

function home(){return `<section class="home"><div class="hero-lockup"><span class="hero-spark">✦</span><p class="eyebrow">Focused prompt generation</p></div><h1 class="hero-title">Turn a rough idea into a prompt that gets it right.</h1><p class="hero-copy">Describe what you want. Perfect Prompt locks the intent, routes it through the full Prompt Master engine, asks only critical questions when needed, repairs failure patterns, validates the result, and gives you one clean instruction ready to use.</p><div class="idea-card"><div class="input-top"><span>What do you want to create?</span><span class="local-badge">Private · local</span></div><textarea id="ideaInput" maxlength="4000" placeholder="Example: Build a simple personal timesheet for one worker with punch in, punch out, history, and a monthly calendar.">${esc(state.idea)}</textarea><div class="idea-footer"><span class="privacy-mini">Full Prompt Master runtime runs locally in this browser</span><button class="primary generate-button" id="generateStart"><span>Generate Prompt</span><b>→</b></button></div></div><div class="validation" id="validation"></div><div class="try-row"><div><strong>Try an idea</strong><span>Start fast, then make it yours.</span></div><button class="more-link" data-open-ideas>More ideas →</button></div><div class="starter-grid"><button class="quick-card" data-quick="Build a simple personal timesheet for one worker with punch in, punch out, live shift time, history, and monthly calendar."><span>◷</span><strong>Smart Timesheet</strong><small>Personal work hours</small></button><button class="quick-card" data-quick="Build a calm personal budgeting app that makes setting and following a budget painless."><span>◇</span><strong>Budget Flow</strong><small>Simple money control</small></button><button class="quick-card" data-quick="Improve an existing mobile app so the main workflow is clearer, faster, and more reliable without adding unrelated features."><span>↗</span><strong>Improve an App</strong><small>Polish what exists</small></button></div></section>`}
function progress(n){return `<div class="progress-wrap"><span>${n}/3</span><div class="progress">${[1,2,3].map(i=>`<i class="${i<=n?'on':''}"></i>`).join('')}</div></div>`}
function wizard(){let body='';if(state.step===1){body=`<div class="choice-list">${goalOptions.map(([v,t,d])=>`<button class="choice ${state.goal===v?'selected':''}" data-goal="${v}"><span><strong>${t}</strong><small>${d}</small></span><span class="radio"></span></button>`).join('')}</div>`}else if(state.step===2){body=`<div class="tag-grid">${priorityOptions.map(([v,t])=>`<button class="tag ${state.priorities.includes(v)?'on':''}" data-priority="${v}">${t}</button>`).join('')}</div><div class="helper-card"><span>Tip</span><p>Choose only what truly matters. Prompt Master will infer non-critical details, route the task, repair known failure patterns, and validate the final prompt before output.</p></div>`}else{body=`<div class="choice-list">${targetOptions.map(([v,t,d])=>`<button class="choice ${state.target===v?'selected':''}" data-target="${v}"><span><strong>${t}</strong><small>${d}</small></span><span class="radio"></span></button>`).join('')}</div>`}const titles=[['What are we doing?','Choose the job. The core intent stays locked.'],['What matters most?','Add the constraints that should shape the result.'],['Where is the prompt going?','Pick a destination or let Prompt Master route it.']][state.step-1];return `<section class="flow"><div class="flow-head"><div><p class="eyebrow">Smart wizard</p><h1>${titles[0]}</h1><p>${titles[1]}</p></div>${progress(state.step)}</div>${body}<div class="wizard-actions"><button class="secondary" data-action="${state.step===1?'home':'back'}">Back</button><button class="primary" id="wizardNext">${state.step===3?'Generate Prompt':'Continue'} <b>→</b></button></div></section>`}
function clarification(){return `<section class="flow"><div class="flow-head"><div><p class="eyebrow">Prompt Master clarification</p><h1>Just the details that actually matter.</h1><p>Prompt Master found ${state.clarifications.length} critical ${state.clarifications.length===1?'gap':'gaps'}. Answer these before compilation so it does not guess.</p></div></div><div class="choice-list">${state.clarifications.map((item,i)=>`<div class="idea-card"><div class="input-top"><span>${esc(item.question)}</span><span class="local-badge">Required</span></div><textarea data-clarification="${i}" maxlength="800" placeholder="Type your answer here">${esc(state.clarificationAnswers[i]||'')}</textarea></div>`).join('')}</div><div class="validation" id="clarificationValidation"></div><div class="wizard-actions"><button class="secondary" data-action="back-to-wizard">Back</button><button class="primary" id="clarificationSubmit">Compile Prompt <b>→</b></button></div></section>`}
function generating(){return `<section class="generating"><div class="generation-card"><div class="orb"><span>✦</span></div><p class="eyebrow">Full Prompt Master Engine</p><h1>Compiling your prompt</h1><p>Extracting all nine intent dimensions, routing by primary task, selecting the right structure, checking all 37 failure patterns, repairing issues, and validating the final instruction.</p><div class="pulse-lines"><i></i><i></i><i></i></div></div></section>`}
function result(){const target=state.meta?.targetLabel||'Optimized route';const template=state.meta?.template||'Prompt Master';const validation=state.meta?.validation?.ok?'Validated':'Needs review';return `<section class="result"><div class="result-celebrate"><span>✓</span><div><p class="eyebrow">${validation}</p><h1>Your prompt is compiled.</h1><p>The full Prompt Master runtime selected, repaired, and validated the prompt locally before showing it.</p></div></div><div class="prompt-card"><div class="prompt-toolbar"><span>${esc(target)} · ${esc(template)}</span><span>Private · local</span></div><div class="prompt-surface" id="promptText">${esc(state.result)}</div></div><div class="result-actions"><button class="primary" id="copyPrompt">Copy Prompt <b>↗</b></button><button class="secondary" id="refinePrompt">Refine</button><button class="secondary" data-action="new">Start New</button></div></section>`}
function ideaLibrary(){return `<section class="library"><div class="library-top"><button class="back-link" data-action="home">← Home</button><p class="eyebrow">Prompt Ideas</p><h1>Useful ideas for real life.</h1><p class="library-sub">Browse practical app concepts. Tap one to load it into the generator and customize it.</p></div>${Object.entries(ideas).map(([cat,list])=>`<section class="library-section"><div class="section-heading"><h2>${cat}</h2><span>${list.length} ideas</span></div><div class="card-grid">${list.map(item=>`<button class="starter-card" data-starter="${esc(item.prompt)}"><span class="card-arrow">↗</span><strong>${esc(item.title)}</strong><p>${esc(item.prompt)}</p></button>`).join('')}</div></section>`).join('')}</section>`}
function templateLibrary(){return `<section class="library"><div class="library-top"><button class="back-link" data-action="home">← Home</button><p class="eyebrow">Prompt Templates</p><h1>Start with a proven structure.</h1><p class="library-sub">Templates are reusable prompt recipes. Prompt Master will still route, diagnose, repair, and validate them before output.</p></div><div class="template-grid">${templates.map(t=>`<button class="template-card" data-starter="${esc(t.prompt)}"><span class="template-category">${esc(t.category)}</span><strong>${esc(t.title)}</strong><p>${esc(t.prompt)}</p><b>Use template →</b></button>`).join('')}</div></section>`}
function settings(){return `<section class="library"><div class="library-top"><button class="back-link" data-action="home">← Home</button><p class="eyebrow">Settings</p><h1>Keep it comfortable.</h1><p class="library-sub">Only useful preferences. No account or cloud history required.</p></div><div class="settings-panel"><div><h2>Appearance</h2><p>Choose a theme or follow your device.</p></div><div class="theme-options">${['system','light','dark'].map(t=>`<button class="theme-option ${state.theme===t?'on':''}" data-theme-choice="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div></div><div class="setting-block"><h3>Prompt privacy</h3><p>Your idea, wizard answers, critical clarification answers, intent analysis, diagnostics, repairs, validation, and generated prompt stay in the browser. No external AI call is required for compilation.</p></div></section>`}
function about(){return `<section class="library"><div class="library-top"><button class="back-link" data-action="home">← Home</button><p class="eyebrow">About</p><h1>Perfect Prompt</h1><p class="library-sub">A deterministic prompt compiler powered exclusively by the Prompt Master runtime and Idea Lock for reliable intent preservation.</p></div><div class="setting-block"><h3>Prompt Master authority</h3><p>The live compiler performs nine-dimension intent extraction, critical-gap clarification, primary-task routing, the complete A–M template library, all 37 failure-pattern diagnostics, deterministic repair, tool/model adaptation, context handling, credential safety, agentic boundaries, and final validation locally in the browser.</p></div><div class="setting-block"><h3>Attribution</h3><p>Prompt-engineering rules are adapted from the MIT-licensed Prompt Master project by Nidhin Joseph Nelson. License and upstream attribution remain in this repository.</p></div></section>`}

function clarifiedTarget(){const gap=state.clarifications.findIndex(x=>x.dimension==='targetTool');if(gap<0)return state.target;const answer=(state.clarificationAnswers[gap]||'').toLowerCase();if(/claude code/.test(answer))return 'claude-code';if(/claude/.test(answer))return 'claude';if(/codex|chatgpt work/.test(answer))return 'codex';if(/chatgpt|openai|gpt/.test(answer))return 'openai';if(/gemini/.test(answer))return 'gemini';if(/grok|xai/.test(answer))return 'grok';if(/cursor|windsurf/.test(answer))return 'cursor-windsurf';if(/cline/.test(answer))return 'cline';if(/comfyui/.test(answer))return 'comfyui';if(/midjourney|dall|stable diffusion|sora|runway|image|video/.test(answer))return 'visual';return answer.trim()||state.target}
function clarificationContext(){return state.clarifications.map((item,i)=>`${item.question} ${state.clarificationAnswers[i]||''}`).join('\n')}
function compile(){return compileWithPromptMaster({idea:state.idea,goal:state.goal,priorities:state.priorities,target:clarifiedTarget(),sessionContext:clarificationContext()})}
function finishCompilation(meta){state.meta=meta;state.result=meta.prompt;state.screen='generating';render();setTimeout(()=>{state.screen='result';render()},700)}
function compileOrClarify(){const meta=compile();if(meta.clarifications?.length&&!state.clarificationAnswers.length){state.meta=meta;state.clarifications=meta.clarifications;state.clarificationAnswers=Array(meta.clarifications.length).fill('');state.screen='clarify';render();return}finishCompilation(meta)}

function bind(){
  $('#ideaInput')?.addEventListener('input',e=>state.idea=e.target.value);
  $('#generateStart')?.addEventListener('click',()=>{state.idea=$('#ideaInput').value.trim();if(!state.idea){$('#validation').textContent='Describe what you want first.';$('#ideaInput').focus();return}state.step=1;clearClarifications();go('wizard')});
  $('[data-open-ideas]')?.addEventListener('click',()=>go('ideas'));document.querySelectorAll('[data-quick]').forEach(b=>b.addEventListener('click',()=>loadStarter(b.dataset.quick)));document.querySelectorAll('[data-starter]').forEach(b=>b.addEventListener('click',()=>loadStarter(b.dataset.starter)));document.querySelectorAll('[data-goal]').forEach(b=>b.addEventListener('click',()=>{state.goal=b.dataset.goal;render()}));document.querySelectorAll('[data-priority]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.priority;state.priorities=state.priorities.includes(v)?state.priorities.filter(x=>x!==v):[...state.priorities,v];render()}));document.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>{state.target=b.dataset.target;render()}));
  $('#wizardNext')?.addEventListener('click',()=>{if(state.step<3){state.step++;render();window.scrollTo({top:0,behavior:'smooth'})}else compileOrClarify()});
  document.querySelectorAll('[data-clarification]').forEach(el=>el.addEventListener('input',e=>state.clarificationAnswers[Number(e.target.dataset.clarification)]=e.target.value));
  $('#clarificationSubmit')?.addEventListener('click',()=>{const answers=[...document.querySelectorAll('[data-clarification]')].map(el=>el.value.trim());state.clarificationAnswers=answers;if(answers.some(x=>!x)){const v=$('#clarificationValidation');if(v)v.textContent='Answer each critical question so Prompt Master does not have to guess.';return}const meta=compile();if(meta.clarifications?.length){const unresolved=meta.clarifications.filter(g=>!state.clarifications.some((old,i)=>old.dimension===g.dimension&&state.clarificationAnswers[i]));if(unresolved.length){state.clarifications=unresolved;state.clarificationAnswers=Array(unresolved.length).fill('');render();return}}finishCompilation(meta)});
  document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='home')go('home');if(a==='back'){state.step=Math.max(1,state.step-1);render()}if(a==='back-to-wizard'){state.screen='wizard';render()}if(a==='new')startNew()}));
  $('#copyPrompt')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(state.result);$('#copyPrompt').innerHTML='Copied ✓';showToast('Prompt copied')}catch{showToast('Select the prompt and copy manually')}});
  $('#refinePrompt')?.addEventListener('click',()=>{state.idea=`Adapt and improve this existing prompt while preserving its core intent and constraints:\n\n${state.result}`;state.goal='improve';state.target='auto';state.step=1;clearClarifications();go('wizard')});document.querySelectorAll('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>{setTheme(b.dataset.themeChoice);render();showToast(`${b.textContent} theme`)}));
}
function render(){if(state.screen==='home')screen.innerHTML=home();else if(state.screen==='wizard')screen.innerHTML=wizard();else if(state.screen==='clarify')screen.innerHTML=clarification();else if(state.screen==='generating')screen.innerHTML=generating();else if(state.screen==='result')screen.innerHTML=result();else if(state.screen==='ideas')screen.innerHTML=ideaLibrary();else if(state.screen==='templates')screen.innerHTML=templateLibrary();else if(state.screen==='settings')screen.innerHTML=settings();else screen.innerHTML=about();bind();syncThemeButtons()}
render();
