export const typeScale={body:16,secondary:14,label:12,button:15,prompt:14};

export const ideas={
  Productivity:[
    {title:'Smart Timesheet',prompt:'Build a premium personal timesheet for one worker. Main flow: Home → Punch In → Active Shift → Punch Out → Saved Day. Home shows today’s date, shift status, a real live elapsed timer, today’s hours, and one large Punch In or Punch Out action. Weekly is a primary view for the Sunday–Friday workweek with daily hours, total hours, hourly rate, gross pay, configurable deductions, and estimated net pay. Include History, Monthly Calendar, holidays, and local persistence. Keep it personal: no teams, GPS, scheduling, employer dashboard, or payroll processing.'},
    {title:'Focus Timer',prompt:'Build a calm personal focus timer for one person. Main flow: Home → Choose Session → Focus → Break → Saved Session. Home shows the next session, today’s focused minutes, and one large Start control. The active screen needs a real countdown, pause/resume, finish-early confirmation, and clear work/break state. Save completed sessions locally and provide Daily History plus a simple Weekly summary. Keep settings limited to focus length, break length, sound, and theme. Avoid task-management, social, team, analytics-dashboard, or account features.'},
    {title:'Task Triage',prompt:'Build a simple personal task triage app for deciding what matters today. Main flow: Home → Add Task → Place in Today or Later → Complete → Done History. Home should center on Today, with quick add, reorder, complete, and move-to-later actions. Later holds deferred tasks without project hierarchy. Save tasks locally, preserve order, and provide a compact completed history with restore. Include useful empty states and edit/delete confirmation. Keep it intentionally lightweight: no projects, teams, kanban boards, collaboration, time tracking, or productivity analytics.'},
    {title:'Meeting Notes',prompt:'Build a fast personal meeting-notes app. Main flow: Home → New Meeting → Capture Agenda and Notes → Record Decisions and Action Items → Save Meeting. The active meeting screen should keep agenda, freeform notes, decisions, action items, owners, and follow-up dates in one clear flow. Saved meetings appear in History with search and detail/edit views. Persist drafts and completed notes locally so navigation or refresh does not lose work. Keep it focused on capture and follow-up; no video calls, team chat, CRM, document suite, or enterprise workspace.'},
    {title:'Daily Planner',prompt:'Build a calm personal day planner. Main flow: Home/Today → Add Priority or Appointment → Work Through Day → End-of-Day Review → Saved Day. Today should show the date, top three priorities, appointments in time order, quick notes, and one obvious add action. Allow complete, edit, reorder, and carry-forward where appropriate. Save each day locally and provide a simple History/Calendar for past days. Keep the experience quiet and focused; no project management, team collaboration, complex recurring automation, productivity scoring, or dashboard clutter.'},
    {title:'Habit Streaks',prompt:'Build a lightweight personal habit tracker. Main flow: Home/Today → Check In Habit → Update Streak → Saved Day → Weekly Progress. Today should list active habits with one-tap completion, current streak, and clear missed/not-done states. Allow creating, editing, reordering, pausing, and archiving habits. Save check-ins locally and derive weekly progress and history from the same records. Optional reminders belong in settings only if supported. Keep it personal and encouraging; no social feed, competition, coaching marketplace, team challenges, or health claims.'}
  ],
  Utility:[
    {title:'Home Inventory',prompt:'Build a private home inventory for one household. Main flow: Home → Add Item → Choose Room → Save Item → Inventory/Search → Item Detail. Each item stores name, room, quantity, purchase date, optional price, photo reference, serial/model information, and notes. Home should surface quick add, recent items, room shortcuts, and search. Allow edit, delete, and move-room actions, with records saved locally. Include useful empty states and simple totals only where relevant. Keep it an inventory tool: no insurance claims, shopping marketplace, cloud accounts, social sharing, or household task management.'},
    {title:'Unit Helper',prompt:'Build a fast everyday unit converter. Main flow: Home → Choose Conversion Category → Enter Value → See Live Result → Swap or Save Recent Conversion. Support cooking, distance, temperature, weight, volume, and common household measurements with correct conversion logic and sensible formatting. Home should make category selection and the input/result pair immediately visible. Keep a small local recent-history list and remember the last category. Handle zero, negatives, decimals, and invalid input cleanly. Keep it a focused utility: no scientific calculator, currency rates, account system, ads, or unrelated reference encyclopedia.'},
    {title:'QR Toolkit',prompt:'Build a simple personal QR toolkit. Main flow: Home → Choose Create or Scan → Enter/Read Content → Preview Result → Save to Library. Creation should support links, plain text, Wi-Fi details, and contact information with validation and a clear generated preview. Scanning should only be included when the target environment supports camera access; otherwise keep creation fully usable. Save generated QR entries locally with labels and recent history. Allow rename, copy content, and delete. Keep it focused: no marketing analytics, tracking pixels, accounts, payments, or campaign management.'},
    {title:'Receipt Keeper',prompt:'Build a private receipt organizer for one person. Main flow: Home → Add Receipt → Enter or Capture Details → Save → Search/History → Receipt Detail. A receipt stores merchant, amount, category, purchase date, optional photo reference, payment note, and memo. Home should show quick add, recent receipts, search, and this month’s total without becoming a finance dashboard. Persist records locally and support edit, delete, filter, and empty states. Keep it strictly for receipt organization: no bank connections, budgeting engine, tax filing, OCR promises, expense reimbursement, or team accounts.'},
    {title:'Checklist Maker',prompt:'Build a reusable personal checklist app. Main flow: Home → Choose Existing List or New Checklist → Check Items → Complete List → Saved Run. Users can create, rename, reorder, edit, and delete checklist items, then reuse the template for packing, errands, maintenance, inspections, or routines. Save templates and completed runs locally, with a simple History showing date and completion status. Home should prioritize recent/favorite lists and one obvious New Checklist action. Keep it lightweight: no project boards, team assignments, chat, complex scheduling, or enterprise inspection workflows.'},
    {title:'Document Expiry',prompt:'Build a personal document-expiry tracker. Main flow: Home → Add Document → Set Expiry Date → Save → Upcoming → Archived/History. Track licenses, registrations, warranties, certifications, and other personal documents with name, category, expiry date, optional identifier, notes, and reminder lead time. Home should clearly show what expires soon, what is current, and one Add Document action. Save records locally and allow edit, renew, archive, delete, and date sorting. Keep it a reminder/reference tool: no legal advice, document storage vault, identity verification, government integration, or business compliance dashboard.'}
  ],
  Finance:[
    {title:'Budget Flow',prompt:'Build a calm personal budgeting app for one person. Main flow: Home → Set Budget → Add Spending → Budgets → Budget Detail. Home should show the current budget, amount spent, amount remaining, and one obvious Add Spending action. Budget Detail lists transactions and updates totals immediately after add, edit, or delete. Save budgets and spending locally and provide a simple monthly history. Use clear money formatting and prevent totals from disagreeing across views. Keep it simple: no bank connections, investment tracking, credit scoring, tax tools, shared household accounts, or spreadsheet-style dashboard clutter.'},
    {title:'Loan Tracker',prompt:'Build a private loan schedule tracker for money lent to another person. Main flow: Home → Add Borrower/Loan → Set Balance and Due Dates → Record Payment → Updated Balance/History. Each loan shows borrower name, starting balance, payment schedule, next due date, paid status, and remaining balance. Marking a payment paid should update the balance and preserve a payment history. Save all records locally unless a backend is explicitly requested. Keep it a tracking tool only: no in-app payments, collections, credit reporting, interest calculation unless entered, legal enforcement, or banking features.'},
    {title:'Bill Calendar',prompt:'Build a personal bill calendar. Main flow: Home → Add Bill → Set Due Date and Amount → Calendar/List → Mark Paid → Monthly History. Home should show upcoming bills, overdue unpaid items, this month’s expected total, and one Add Bill action. Support recurring bills, edit, paid/unpaid toggle, and clear status changes. Save bills locally and derive calendar and monthly totals from the same records. Make dates and money easy to scan on mobile. Keep it focused: no bank sync, autopay, budgeting system, credit monitoring, household sharing, or financial-advice features.'},
    {title:'Savings Goal',prompt:'Build a focused personal savings-goal app. Main flow: Home → Create Goal → Add Deposit → Updated Progress → Goal History. Each goal stores name, target amount, optional deadline, starting amount, and deposits. Home should show active goals, progress, remaining amount, and one obvious Add Deposit action for the selected goal. Every deposit must update totals and progress immediately; allow edit/delete with recalculation. Save goals and deposit history locally. Keep it motivational but simple: no bank connection, investing, interest projections, financial advice, social challenges, or complex budgeting.'},
    {title:'Subscription Check',prompt:'Build a private subscription tracker. Main flow: Home → Add Subscription → Set Cost and Renewal → Active List → Mark Canceled or Edit → History. Track service name, amount, billing frequency, renewal date, category, and cancellation status. Home should show upcoming renewals, estimated monthly cost, and one Add Subscription action. Normalize recurring costs carefully for the monthly estimate and keep canceled items out of active totals. Save records locally with search/filter and history. Keep it informational: no bank scanning, automatic cancellation, negotiation service, payments, shared accounts, or financial dashboard clutter.'},
    {title:'Cash Envelope',prompt:'Build a simple digital cash-envelope budget for one person. Main flow: Home → Set Monthly Income/Available Amount → Create Envelopes → Add Spending → Updated Envelope Balance. Home should show each envelope’s allocated, spent, and remaining amount plus an overall unallocated total. Support add, edit, transfer between envelopes, and spending history with calculations that remain consistent. Save the current month and past months locally. Use clear warnings for overspending without blocking valid edits. Keep it focused: no bank sync, credit tools, investment features, family permissions, or spreadsheet-style accounting.'}
  ],
  Personal:[
    {title:'Daily Notes',prompt:'Build a private day-based quick-notes app. Main flow: Home/Today → Add Note → Save → Browse Days/Search → Note Detail/Edit. Today should make quick capture immediate and show notes in time order with pin/favorite options. Save drafts and notes locally, support edit/delete, and provide search across note text plus a simple date history. Keep formatting lightweight and mobile-friendly. Empty states should invite capture without clutter. Keep it personal: no social sharing, collaborative documents, public publishing, AI writing assistant, complex folders, or account system.'},
    {title:'Routine Keeper',prompt:'Build a simple personal routine checklist. Main flow: Home/Today → Choose Routine → Complete Steps → Finish Routine → Saved Completion. Users can create reusable morning, evening, work, or custom routines with ordered steps. During a routine, show progress and one clear next action; allow checking/unchecking steps before completion. Save routine templates and completion history locally and show a compact weekly consistency view. Support edit, reorder, pause, and archive. Keep it focused: no habit social network, coaching, team routines, calendar replacement, or complex automation.'},
    {title:'Gift List',prompt:'Build a private gift planner for one person. Main flow: Home → Choose Person/Occasion → Add Gift Idea → Mark Purchased → Saved Gift History. Track person, occasion, date, ideas, estimated budget, actual amount, purchased status, and optional notes. Home should show upcoming occasions, people, and one quick Add Idea action. Save records locally, allow edit/delete, filter purchased vs ideas, and calculate simple totals per occasion. Keep it discreet and lightweight: no shopping marketplace, affiliate links, payments, shared wish lists, contacts sync, or social features.'},
    {title:'Home Chores',prompt:'Build a simple household chore planner. Main flow: Home/This Week → Add Chore → Assign Day/Person → Mark Complete → Weekly Reset/History. Show chores grouped by day with clear ownership and completion state, plus one Add Chore action. Support recurring chores, edit, reassign, skip, and complete. Save chore definitions and completion history locally so weekly progress remains consistent. Keep assignments simple for a small household. Avoid turning it into project management: no chat, points economy, complex permissions, employee scheduling, or enterprise facility features.'},
    {title:'Contact Notes',prompt:'Build a private personal relationship-notes app. Main flow: Home → Add Person → Save Important Detail or Follow-up → Person Detail → Search/Recent. Each person can hold notes, important dates, last contact, next follow-up, and small remembered details. Home should prioritize recent people and upcoming follow-ups with one Add Person action. Save everything locally, support edit/delete, and keep a chronological note history per person. Keep privacy and simplicity central: no address-book replacement, messaging, CRM pipelines, sales metrics, social scraping, or automatic contact syncing.'},
    {title:'Memory Jar',prompt:'Build a private memory journal. Main flow: Home → Add Memory → Attach Date/Tags/Optional Photo Reference → Save → Browse/Search → Resurface Memory. Home should invite one quick memory capture and optionally show a random saved memory. Each entry keeps text, date, tags, and optional photo reference. Save entries locally, support edit/delete/favorite, search, and chronological history. Random resurfacing must select only from saved entries. Keep it intimate and calm: no social feed, public sharing, follower system, AI-generated memories, cloud account requirement, or analytics.'}
  ],
  Work:[
    {title:'Drop & Hook Assistant',prompt:'Build a personal mobile work app for one truck driver completing multiple drop-and-hook stops in one day. Main flow: Home → Start My Day → Day Setup → Create Route → Start Route → Work Mode → Day Complete. Day Setup collects truck/unit, starting mileage, and optional current trailer. Create Route supports add/search/select/reorder stops. Work Mode shows business name, address, arrival/departure, plus an attached collapsible Drop & Hook section for drop trailer, hook trailer, seal, and reference. Save the active day locally. Keep it personal: no fleet, dispatch, ELD, in-app map, notes field, or latitude/longitude display.'},
    {title:'Shift Handoff',prompt:'Build a concise shift-handoff tool for one work area. Main flow: Home → New Handoff → Record Open Items, Completed Work, Blockers, and Next Actions → Review → Save Handoff. The active form should keep those sections distinct, support quick edits, and make incomplete critical items visible before saving. Saved handoffs appear in History with date/time, shift label, search, and detail view. Persist drafts locally so work is not lost. Keep it concise: no team chat, scheduling, ticketing system, performance metrics, enterprise workflow engine, or large operations dashboard.'},
    {title:'Mileage Log',prompt:'Build a personal work-mileage tracker. Main flow: Home → Start Trip → Enter Start Mileage/Purpose → End Trip → Enter End Mileage → Saved Trip. Calculate trip miles from start/end values, validate impossible entries, and show the active trip clearly. Home should show today’s miles, current trip status, and one Start/End Trip action. Save trips locally with History and monthly totals; allow edit with recalculation. Keep it a mileage log: no GPS tracking, route maps, fuel accounting, tax filing, fleet management, or employer monitoring.'},
    {title:'Job Site Log',prompt:'Build a simple personal field-work log. Main flow: Home → New Site Visit → Arrive → Record Work/Materials/Photos/Notes → Depart → Saved Visit. Each visit stores site name, date, arrival/departure times, work completed, materials used, optional photo references, and notes. Home should show today’s visits and one New Visit action. Save active and completed visits locally, support edit/search, and provide chronological History. Keep it a personal record: no dispatch, invoicing, CRM, workforce scheduling, live location tracking, or construction-management dashboard.'},
    {title:'Client Follow-up',prompt:'Build a lightweight personal client follow-up tracker. Main flow: Home → Add Client → Record Contact → Set Next Action/Due Date → Mark Complete → Updated Client History. Each client shows last contact, next action, due date, status, and notes. Home should prioritize due and overdue follow-ups plus one Add Client action. Save clients and contact history locally; allow edit, search, archive, and completed follow-up history. Keep it deliberately small: no sales pipeline, email sending, CRM automation, team permissions, revenue analytics, or marketing campaigns.'},
    {title:'Equipment Check',prompt:'Build a repeatable personal equipment-inspection app. Main flow: Home → Choose Equipment/Checklist → Start Inspection → Mark Each Item → Record Issue/Optional Photo → Complete → Saved Record. Show inspection progress and prevent accidental completion while required items are unanswered. Support reusable checklists, condition choices, issue notes, optional photo references, and a final summary. Save templates and completed inspections locally with history/search. Keep it a simple inspection record: no maintenance dispatch, compliance certification, fleet telematics, inventory purchasing, team assignments, or enterprise asset dashboard.'}
  ],
  Health:[
    {title:'Water Tracker',prompt:'Build a simple personal hydration tracker. Main flow: Home/Today → Quick Add Water → Updated Progress → Daily Complete → History. Home should show today’s goal, consumed amount, remaining amount, and large quick-add choices with undo. Allow a custom amount and editable daily goal. Save daily totals locally and provide recent history plus a compact weekly view derived from the same records. Keep language neutral and avoid medical claims. No social competition, nutrition platform, wearable integration, diagnosis, coaching marketplace, or account requirement.'},
    {title:'Walking Log',prompt:'Build a lightweight personal walking log. Main flow: Home → Add Walk → Enter Time/Distance/Notes → Save → Weekly Progress/History. Home should show today’s and this week’s walking totals with one Add Walk action. Each record stores date, duration, distance, and optional note; allow edit/delete with totals recalculated. Save walks locally and derive weekly summaries from the same records. Keep it manual and private: no GPS route tracking, maps, social challenges, calorie or medical claims, wearable integration, or training plan.'},
    {title:'Meal Rhythm',prompt:'Build a simple personal meal-planning app. Main flow: Home/Week → Choose Day → Plan Breakfast/Lunch/Dinner → Add Grocery Notes → Save Week. The weekly view should make meals easy to scan and allow copying a favorite meal into another slot. Maintain a small Favorites library and a grocery-notes list derived from planned meals only when explicitly added. Save plans and favorites locally. Keep it practical and low-pressure: no calorie counting, dieting advice, medical nutrition claims, grocery ordering, recipe social network, or household account complexity.'},
    {title:'Sleep Notes',prompt:'Build a private personal sleep log. Main flow: Home → Add Sleep Entry → Set Bedtime/Wake Time/Quality/Note → Save → Weekly Patterns/History. Calculate sleep duration from valid times and make overnight spans work correctly. Home should show the latest entry and simple recent averages without medical interpretation. Save entries locally, support edit/delete, and derive weekly patterns from the same records. Keep wording observational, not diagnostic. No sleep scoring claims, treatment advice, wearable integration, alarms, social sharing, or health-provider dashboard.'},
    {title:'Medication List',prompt:'Build a private personal medication reference list. Main flow: Home → Add Medication → Enter Name/Dosage/Schedule/Refill Date → Save → Medication Detail/List. Home should clearly show current medications and upcoming refill dates with one Add Medication action. Save entries locally and support edit, archive, delete, and optional simple reminder setup only if the environment supports it. Treat all information as user-entered reference data. Keep it non-clinical: no diagnosis, dosage recommendations, drug interaction advice, prescribing, pharmacy ordering, or emergency guidance.'},
    {title:'Mood Check-in',prompt:'Build a private daily mood check-in app. Main flow: Home/Today → Choose Mood Rating → Add Optional Note/Tags → Save Check-in → Weekly Trend/History. Make check-in fast, with one clear rating control and optional detail rather than a long form. Save entries locally and show a simple weekly trend based only on user-entered ratings; support edit/delete. Keep the tone neutral and non-judgmental. No diagnosis, mental-health scoring claims, therapy replacement, crisis assessment, social feed, public sharing, or gamified streak pressure.'}
  ],
  Tracking:[
    {title:'Maintenance Log',prompt:'Build a personal maintenance tracker for a vehicle or piece of equipment. Main flow: Home → Add Asset → Record Service → Save → Upcoming Maintenance → Service History. Track service date, mileage/hours, service type, cost, notes, and next due mileage/date when entered. Home should show what is due soon and one Record Service action. Save assets and service records locally; edits must recalculate upcoming status. Keep it a record/reminder tool: no repair diagnostics, parts marketplace, fleet management, telematics, shop scheduling, or manufacturer integration.'},
    {title:'Package List',prompt:'Build a private manual package tracker. Main flow: Home → Add Expected Package → Update Status Note → Mark Received → Received History. Each package stores label/item, carrier, optional tracking number, expected date, status note, and received date. Home should separate expected, late, and recently received items with one Add Package action. Save entries locally, support edit/search/delete, and keep status user-controlled unless a carrier integration is explicitly requested. No automatic carrier scraping, shopping marketplace, delivery map, account system, or purchase-history import.'},
    {title:'Warranty Tracker',prompt:'Build a personal warranty organizer. Main flow: Home → Add Product → Enter Purchase/Warranty Details → Save → Expiring Soon → Product Detail/Service History. Store product name, purchase date, warranty end date, optional receipt reference, serial number, seller, and service notes. Home should surface warranties expiring soon and one Add Product action. Save records locally, allow edit/archive/delete, and keep service notes chronological. Keep it an organizer only: no claim filing, manufacturer portal integration, legal advice, shopping marketplace, cloud document vault, or household team system.'},
    {title:'Pet Care Log',prompt:'Build a personal pet-care tracker. Main flow: Home → Choose Pet → Add Care Entry → Save → Pet Timeline/Upcoming Items. Track user-entered feeding notes, medication logs, grooming, appointments, weight, and general notes in a chronological timeline. Home should show pets, recent entries, and upcoming user-entered dates with one Add Entry action. Save records locally and support edit/search. Keep it informational and owner-entered: no diagnosis, veterinary advice, dosage recommendations, emergency triage, social pet network, marketplace, or clinic-management features.'},
    {title:'Fuel Log',prompt:'Build a personal vehicle fuel log. Main flow: Home → Add Fill-up → Enter Odometer/Gallons/Cost/Station → Save → MPG/History. Validate odometer progression and calculate MPG only when enough valid consecutive fill-up data exists. Home should show the latest fill-up, recent MPG, and monthly fuel spend without becoming a finance dashboard. Save fill-ups locally; edit/delete must recalculate dependent MPG values and totals. Keep it a manual log: no GPS, gas-price scraping, route planning, maintenance system, fleet management, or payment features.'},
    {title:'Collection Catalog',prompt:'Build a personal collection catalog. Main flow: Home → Add Item → Enter Category/Condition/Value/Optional Photo → Save → Browse/Search → Item Detail. Home should highlight quick add, categories, recent items, and search. Save items locally with name, category, condition, optional estimated value, photo reference, acquisition date, and notes. Support edit/delete/favorite and simple category/value totals only where useful. Keep it a private catalog: no marketplace, auctions, price scraping, social showcase, insurance appraisal, authentication system, or inventory-for-sale workflow.'}
  ]
};

export const templates=[
  {title:'Build a focused app',category:'Build',prompt:'Build a premium mobile-first app for [PURPOSE] for [TARGET USER]. Define the main workflow as [START] → [CORE ACTIONS] → [RESULT], then specify the minimum screens/views needed to support it. Describe the working behavior, important states, calculations, and persistence requirements for each requested feature. Give a clear visual direction and mobile interaction hierarchy. Lock scope with explicit exclusions so the build does not become a dashboard or unrelated product. Done when the full workflow works end to end with no placeholder controls.'},
  {title:'Improve an existing app',category:'Improve',prompt:'Upgrade my existing [APP/FEATURE] without changing its core purpose. Current problem: [PROBLEM]. Desired behavior: [TARGET]. Preserve [DO NOT CHANGE], including working flows, data, and visual identity that are already correct. Identify the exact screen, interaction, or logic that must change; define before/after behavior and important states. Keep scope narrow, avoid unrelated redesigns or new services, and verify the changed workflow end to end. Done when [SUCCESS CRITERIA] is demonstrably true.'},
  {title:'Fix a specific bug',category:'Fix',prompt:'Fix [BUG] in [FILE/FEATURE]. Current behavior: [CURRENT]. Expected behavior: [EXPECTED]. Reproduce or inspect the failure first, then make the smallest reversible change that corrects the root cause. Do not change unrelated UI, architecture, dependencies, data contracts, or behavior. Cover relevant edge cases and preserve existing working states. Run the most relevant tests/build checks after the change and report concrete verification evidence. Done when the bug no longer reproduces and related behavior remains intact.'},
  {title:'Research and compare',category:'Research',prompt:'Research [TOPIC/OPTIONS] for [GOAL] and compare them using [DECISION CRITERIA]. Use current reliable sources when facts may have changed, distinguish verified evidence from assumptions, and surface important counter-evidence or uncertainty rather than smoothing it over. Compare the options on the same criteria, explain meaningful trade-offs, and avoid irrelevant feature lists. Finish with one recommendation for [TARGET USER/CONTEXT], why it wins, when another option would be better, and what remains uncertain.'},
  {title:'Write professional copy',category:'Writing',prompt:'Write [CONTENT TYPE] for [AUDIENCE] about [SUBJECT]. The goal is [OUTCOME]. Use a [TONE] voice and [LENGTH/FORMAT], preserving any required facts, names, calls to action, or brand language in [SOURCE/NOTES]. Structure the copy for how the audience will actually read or use it, remove filler and generic marketing language, and do not invent unsupported claims. Return finished copy ready to use, plus alternatives only if variants were explicitly requested.'},
  {title:'Create an image prompt',category:'Visual',prompt:'Create a production-ready image-generation prompt for [SUBJECT] in [STYLE]. Define the subject, action/pose, setting, composition, camera/framing where relevant, lighting, mood, material/texture detail, and [ASPECT RATIO]. Preserve [MUST KEEP] and explicitly exclude [UNWANTED ELEMENTS]. Prioritize one clear focal composition rather than a pile of adjectives. Do not invent text, logos, people, products, or background objects that conflict with the brief. Return one clean prompt ready for the target image tool.'},
  {title:'Plan a workflow',category:'Planning',prompt:'Design a practical workflow for [PROCESS] from [STARTING STATE] to [END STATE]. Identify the primary actor, one main objective, required inputs, sequential actions, decision points, error/exception handling, saved state, and completion criteria. Keep optional paths secondary and make the next action obvious at each stage. Remove redundant handoffs or steps that do not change the outcome. Do not add teams, approvals, systems, or automation unless required. Finish with a concise end-to-end flow and the rules needed to implement it reliably.'},
  {title:'Turn notes into a spec',category:'Product',prompt:'Turn these rough notes into an implementation-ready product specification: [NOTES]. Lock the purpose, target user, one main job, primary workflow, screen hierarchy, core features, interaction rules, data/persistence behavior, calculations, empty/active/completed/error states, visual direction, technical constraints, exclusions, and done criteria. Resolve obvious implications conservatively but do not invent unrelated features, services, dashboards, or business logic. Make every visible feature testable and every screen purposeful. Return a clean spec a builder can execute without guessing the product architecture.'}
];

export const buildResultActions=()=>['Copy Prompt','Refine','Start New'];
