import { z } from 'zod';
export const InputSchema=z.object({idea:z.string().min(10)}); export type Input=z.infer<typeof InputSchema>;
export type IdeaLock={primaryJob:string;targetUser:string;platform:string;mainWorkflow:string;requiredFeatures:string[];optionalFeatures:string[];constraints:string[];explicitExclusions:string[];userInstructions:string[]};
export type Prompt={role:string;mission:string;lock:IdeaLock;targetUser:string;platform:string;workflow:string;screens:string[];features:string[];states:string[];visual:string;constraints:string[];doNotAdd:string[];completion:string};
const split=(s:string)=>s.split(/,| and |;|\n/).map(x=>x.trim()).filter(Boolean);
export function parseIdea(raw:string):IdeaLock { const text=InputSchema.parse({idea:raw}).idea; const lower=text.toLowerCase(); const platform=/android|ios|mobile|phone/i.test(text)?(/ios/i.test(text)?'iOS mobile':'Android mobile'):'responsive web'; const target=/for ([^.]+)/i.exec(text)?.[1]?.trim()||'people who need a simple, focused tool'; const job=text.replace(/^.*?(?:build|create|make)\s+(?:an?\s+)?/i,'').split(/\s+for\s+/i)[0].trim()||text; const exclusions=(/do not|don't|without|no /i.test(text)?split(text.match(/(?:do not|don't|without|no )(.+)/i)?.[1]||''):[]); const required=split((/must have|required|include[s]?|with\s+(.+)/i.exec(text)?.[1]||'')).filter(x=>!exclusions.some(e=>x.toLowerCase().includes(e.toLowerCase()))).slice(0,8); return {primaryJob:job,targetUser:target,platform,mainWorkflow:`Open the app, complete the primary task, and confirm the result.`,requiredFeatures:required.length?required:['a clear primary action'],optionalFeatures:[],constraints:['Keep the experience focused and mobile-first'],explicitExclusions:exclusions,userInstructions:[text]}; }
export function compile(raw:string):Prompt { const lock=Object.freeze(parseIdea(raw)) as IdeaLock; const screens=['Home / primary task','Details or editor','Success / confirmation']; const features=lock.requiredFeatures; return {role:'You are a senior product designer and frontend engineer.',mission:`Design a polished product that helps ${lock.targetUser} ${lock.primaryJob}.`,lock,targetUser:lock.targetUser,platform:lock.platform,workflow:lock.mainWorkflow,screens,features,states:['Loading, empty, error, success, and disabled states must be explicit.','Validate inputs inline and preserve user progress.'],visual:'Premium Android-style mobile UI: calm contrast, generous spacing, crisp typography, purposeful color, and accessible touch targets.',constraints:lock.constraints,doNotAdd:[...lock.explicitExclusions,'Unrequested authentication, payments, social features, or settings.'],completion:'The primary workflow is complete, testable, responsive at 360–430px, and every required feature works.'}; }
export function assemble(p:Prompt){return ['Role',p.role,'Product Mission',p.mission,'Idea Lock',`Primary job: ${p.lock.primaryJob}\nTarget user: ${p.lock.targetUser}\nPlatform: ${p.lock.platform}\nRequired: ${p.lock.requiredFeatures.join(', ')}`,'Target User',p.targetUser,'Platform',p.platform,'Main Workflow',p.workflow,'Screen Requirements',p.screens.map((s,i)=>`${i+1}. ${s}`).join('\n'),'Core Features',p.features.map(x=>`• ${x}`).join('\n'),'Interaction & State Rules',p.states.join('\n'),'Visual Direction',p.visual,'Constraints',p.constraints.join('\n'),'Do Not Add',p.doNotAdd.join('\n'),'Completion Standard',p.completion].join('\n\n');}
export function validate(p:Prompt, output:string){const required=['Role','Product Mission','Idea Lock','Target User','Platform','Main Workflow','Screen Requirements','Core Features','Interaction & State Rules','Visual Direction','Constraints','Do Not Add','Completion Standard']; const missing=required.filter(x=>!output.includes(x)); if(missing.length)throw new Error(`Missing sections: ${missing.join(', ')}`); for(const x of p.lock.explicitExclusions)if(output.toLowerCase().includes(x.toLowerCase()))throw new Error(`Exclusion violation: ${x}`); return true;}
export function generate(raw:string){const p=compile(raw);const output=assemble(p);validate(p,output);return output;}
